### ISSUE TITLE
Project is missing .bowerrc and .jshintrc

### ISSUE THREAD

**Issue by john-k-ge** [DigitalTwin/steam-turbine-tutorial-vis#1]
Without the .bowerrc, the bower_components are saved under the project root, not `public`.  As a result, the `grunt dist` fails during the vulcanize step.  Also, the missing .jshintrc prevents anyone from even running a successful `grunt dist`.

**Comment by steubeng** [comment]
Hi John-k-ge,
   This has been fixed and the patch just got merged with master.  Thanks for bringing it to our attention (I ran into it about two weeks ago myself too!)...
